version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8008:8008"
    volumes:
      - ./backend:/app
      - backend_data:/app/app/data
      - resume_storage:/app/app/resumes
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8008 --reload

volumes:
  backend_data:
  resume_storage: